// based on AIRLY_CAQI
export const levels = [
  {
    minValue: 0,
    maxValue: 25,
    values: '0-25',
    level: 'VERY_LOW',
    description: 'Very Low',
    color: '#6BC926',
  },
  {
    minValue: 25,
    maxValue: 50,
    values: '25-50',
    level: 'LOW',
    description: 'Low',
    color: '#D1CF1E',
  },
  {
    minValue: 50,
    maxValue: 75,
    values: '50-75',
    level: 'MEDIUM',
    description: 'Medium',
    color: '#EFBB0F',
  },
  {
    minValue: 75,
    maxValue: 87.5,
    values: '75-87.5',
    level: 'HIGH',
    description: 'High',
    color: '#EF7120',
  },
  {
    minValue: 87.5,
    maxValue: 100,
    values: '87.5-100',
    level: 'VERY_HIGH',
    description: 'Very High',
    color: '#EF2A36',
  },
  {
    minValue: 100,
    maxValue: 125,
    values: '100-125',
    level: 'EXTREME',
    description: 'Extreme',
    color: '#B00057',
  },
  {
    minValue: 125,
    maxValue: null,
    values: '125+',
    level: 'AIRMAGEDDON',
    description: 'Airmageddon!',
    color: '#770078',
  },
  {
    minValue: null,
    maxValue: null,
    values: 'null',
    level: 'null',
    description: 'Lack of Data',
    color: '#5A5E60',
  },
];
